import { MaintenanceTicket, MaintenanceCategory, TicketStatus } from './types';
import { subDays, subHours } from 'date-fns';
const now = new Date();
export const MOCK_TICKETS: MaintenanceTicket[] = [
  {
    id: 't1',
    title: 'Burst Pipe in Science Lab',
    description: 'Major water leak under the main sink in Lab 4. Risk of equipment damage.',
    location: 'Science Building, Room 402',
    category: 'Plumbing & sanitary',
    status: 'In Progress / Pending',
    priority: 'Urgent',
    reporter: 'Dr. Smith',
    contractorName: 'QuickFix Plumbing',
    createdAt: subDays(now, 1).toISOString(),
    updatedAt: subHours(now, 2).toISOString(),
    initialPhotoUrl: 'https://images.unsplash.com/photo-1585704032915-c3400ca1f963?q=80&w=400&auto=format&fit=crop'
  },
  {
    id: 't2',
    title: 'Broken Elevator',
    description: 'Elevator B is stuck on the 3rd floor. Not responding to calls.',
    location: 'Main Library',
    category: 'Electrical',
    status: 'In Progress / Pending',
    priority: 'High',
    reporter: 'John Librarian',
    contractorName: 'Otis Maintenance',
    createdAt: subDays(now, 4).toISOString(), // Stagnant (>48h)
    updatedAt: subDays(now, 3).toISOString(),
  },
  {
    id: 't3',
    title: 'Flickering Lights',
    description: 'All lights in the hallway are flickering constantly.',
    location: 'Arts Wing, Hallway 2',
    category: 'Electrical',
    status: 'In Progress / Pending',
    priority: 'Medium',
    reporter: 'Staff Sarah',
    createdAt: subDays(now, 3).toISOString(), // Stagnant
    updatedAt: subDays(now, 3).toISOString(),
  },
  {
    id: 't4',
    title: 'Graffiti Removal',
    description: 'Graffiti on the north wall of the gym.',
    location: 'Sports Center',
    category: 'Civil',
    status: 'Rectified',
    priority: 'Low',
    reporter: 'Coach Mike',
    contractorName: 'CleanTeam',
    createdAt: subDays(now, 5).toISOString(),
    updatedAt: subDays(now, 1).toISOString(),
  },
  {
    id: 't5',
    title: 'A/C Unit Noise',
    description: 'Extremely loud grinding noise coming from the vent.',
    location: 'Administration, Office 12',
    category: 'Mechanical / HVAC',
    status: 'In Progress / Pending',
    priority: 'High',
    reporter: 'Admin Alice',
    contractorName: 'CoolAir Solutions',
    createdAt: subDays(now, 0.5).toISOString(),
    updatedAt: subHours(now, 1).toISOString(),
  },
  {
    id: 't6',
    title: 'Leaking Roof',
    description: 'Water dripping from ceiling tiles during rain.',
    location: 'Student Union, Lounge',
    category: 'Other',
    status: 'In Progress / Pending',
    priority: 'High',
    reporter: 'Dave S.',
    contractorName: 'RoofMasters',
    createdAt: subDays(now, 10).toISOString(),
    updatedAt: subDays(now, 4).toISOString(), // Stagnant
  },
  {
    id: 't7',
    title: 'Broken Door Handle',
    description: 'Entry door handle is loose and hard to turn.',
    location: 'Dormitory C, Main Entry',
    category: 'Building Structural',
    status: 'In Progress / Pending',
    priority: 'Medium',
    reporter: 'RA Rebecca',
    createdAt: subHours(now, 5).toISOString(),
    updatedAt: subHours(now, 5).toISOString(),
  },
  {
    id: 't8',
    title: 'Loose Paving Stone',
    description: 'Trip hazard on the main walkway near the fountain.',
    location: 'Quad',
    category: 'Civil',
    status: 'In Progress / Pending',
    priority: 'High',
    reporter: 'Grounds Crew',
    contractorName: 'GreenScape',
    createdAt: subDays(now, 2).toISOString(),
    updatedAt: subHours(now, 2).toISOString(),
  },
  {
    id: 't9',
    title: 'Keycard Reader Failure',
    description: 'Reader not accepting any valid cards.',
    location: 'IT Server Room',
    category: 'Security & Safety',
    status: 'In Progress / Pending',
    priority: 'Urgent',
    reporter: 'IT Dept',
    contractorName: 'Securitas',
    createdAt: subDays(now, 1).toISOString(),
    updatedAt: subHours(now, 4).toISOString(),
  },
  {
    id: 't10',
    title: 'Heating Malfunction',
    description: 'Radiators are cold in the entire wing.',
    location: 'History Building, West Wing',
    category: 'Mechanical / HVAC',
    status: 'In Progress / Pending',
    priority: 'High',
    reporter: 'Prof. X',
    createdAt: subDays(now, 6).toISOString(), // Stagnant
    updatedAt: subDays(now, 6).toISOString(),
  }
];
// Compatibility exports for existing template code
export const MOCK_USERS = [{ id: 'u1', name: 'Admin User' }];
export const MOCK_CHATS = [];
export const MOCK_CHAT_MESSAGES = [];